import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { lazy, Suspense, useEffect, useState } from "react";
import { useAuth } from "@/lib/auth";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { t } from "@/lib/i18n";
import { EditorSkeleton } from "@/components/EditorSkeleton";
import type { TestDraft, QuestionDraft } from "@/components/QuizEditor";

const QuizEditor = lazy(() => import("@/components/QuizEditor").then((m) => ({ default: m.QuizEditor })));

export const Route = createFileRoute("/quiz/new")({
  head: () => ({ meta: [{ title: t.newQuiz.metaTitle }] }),
  component: NewQuizPage,
});

function NewQuizPage() {
  const { user, loading } = useAuth();
  const navigate = useNavigate();

  useEffect(() => {
    if (!loading && !user) navigate({ to: "/login" });
  }, [user, loading, navigate]);

  async function handleSubmit(test: TestDraft, questions: QuestionDraft[]) {
    if (!user) return;
    try {
      const { data: created, error } = await supabase
        .from("tests")
        .insert({
          creator_id: user.id,
          title: test.title.trim(),
          description: test.description.trim() || null,
          time_limit: Math.max(60, test.time_limit_min * 60),
          random_enabled: test.random_enabled,
          max_attempts: test.max_attempts,
          questions_per_attempt: test.questions_per_attempt,
          // test_code is auto-generated by DB trigger; pass empty string and let trigger replace
          test_code: "" as unknown as string,
        } as any)
        .select("id, test_code")
        .single();
      if (error || !created) {
        toast.error(t.err.saveFailed);
        return;
      }

      if (questions.length > 0) {
        const rows = questions.map((q, idx) => ({
          test_id: created.id,
          question_text: q.question_text.trim(),
          options: q.options.map((o) => o.trim()),
          correct_answer_index: q.correct_answer_index,
          explanation: (q.explanation ?? "").trim() || null,
          position: idx,
        }));
        const { error: qErr } = await supabase.from("questions").insert(rows);
        if (qErr) {
          toast.error(t.err.saveFailed);
          return;
        }
      }
      toast.success(t.newQuiz.success);
      navigate({ to: "/quiz/$id/edit", params: { id: created.id } });
    } catch {
      toast.error(t.err.network);
    }
  }

  if (loading || !user) {
    return (
      <div className="mx-auto max-w-3xl px-4 py-12">
        <EditorSkeleton />
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-3xl px-4 py-12">
      <h1 className="mb-8 font-display text-3xl font-semibold sm:text-4xl">{t.newQuiz.title}</h1>
      <Suspense fallback={<EditorSkeleton />}>
        <QuizEditor
          initialTest={{
            title: "",
            description: "",
            time_limit_min: 10,
            random_enabled: false,
            max_attempts: 1,
            questions_per_attempt: null,
          }}
          initialQuestions={[]}
          submitLabel={t.newQuiz.submit}
          testCode={null}
          onSubmit={handleSubmit}
        />
      </Suspense>
    </div>
  );
}
